name: Sync WFS to AGOL

on:
  schedule:
    - cron: '0 3 1 * *'  # Runs monthly on the 1st at 03:00 UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install geopandas arcgis

      - name: Run update script
        env:
          AGOL_USERNAME: ${{ secrets.AGOL_USERNAME }}
          AGOL_PASSWORD: ${{ secrets.AGOL_PASSWORD }}
        run: python update_wfs_to_agol.py
